services:
  python_api:
    container_name: python_api
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    # Volume is needed to be able to reload the app in real time with every change inside of /src
    volumes:
      - .:/app
    build:
      context: .
      args:
        - INTERNAL_PORT=${INTERNAL_PORT}
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "${INTERNAL_PORT}"]